version: '3'

services:
  db:
    container_name: docker-lamp_db_1
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: my_secret_pw_shh
      MYSQL_DATABASE: Jpanel
      MYSQL_USER: juser
      MYSQL_PASSWORD: 123
    ports:
      - "9906:3306"
  web:
    #image: php:7.2.2-apache
    container_name: Jrw_php_app
    depends_on:
      - db
    build:
      context: ./
      dockerfile: apache-Dockerfile
    volumes:
      - ./app/:/var/www/html/
    ports:
      - "8100:80"
    stdin_open: true
    tty: true
